#!/bin/sh

# This script is a part of the status bar. It displays active keyboard layout.

set -oue pipefail

CURRENT_KBD_LAYOUT="$(setxkbmap -query | grep layout | awk '{ print $2 }' | tr '[:lower:]' '[:upper:]')"
KBD_ICON=""
printf " %s %s\\n" "${KBD_ICON}" "${CURRENT_KBD_LAYOUT}"
